### ISSUE TITLE
Multiple events sending at once

### ISSUE THREAD

**Issue by JunaidAK** [eealeivan/mixpanel-csharp#7] opened 2017-07-13 13:11 UTC
We are using this library and it seems some users are throwing multiple events (approximately 100 events) of same name at a single second, however the track method is called only once. Either there is a problem in this library or in the mix panel server side handling. Please look into this issue at your end and update me ASAP.

**Comment by eealeivan** [comment] 2017-07-13 18:07
Hi,
Can you please provide some code samples? What method do you use? What platform are you using?

I created a simple console application and 100 messages were successfully sent to Mixpanel:
```csharp
var mixpanelClient = new MixpanelClient("TOKEN");
for (int i = 0; i < 100; i++)
{
    mixpanelClient.Track("Test", new { A = "B" });
}
```

**Comment by eealeivan** [comment] 2017-07-31 19:54
I'm closing this issue because I was not able to reproduce it and didn't get any additional info from reporter.

**Closed by eealeivan** 2017-07-31 19:54 UTC
